server:
  # 端口号
  port: 8761

spring:
  application:
    # 应用名称
    name: eureka-server

# 配置Eureka Server注册中心
eureka:
  instance:
    # 主机名, 不配置的时候将根据操作系统的主机名称来获取
    hostname: localhost
    # 是否开启IP地址注册
    prefer-ip-address: true
    # 主机地址+端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 指定注册主机地址
    ip-address: ${spring.cloud.client.ip-address}
  client:
    # 是否将自己注册到注册中心,默认为true
    registerWithEureka: true
    # 是否从注册中心获取服务注册信息,默认为true
    fetchRegistry: true
    serviceUrl:
      # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8762/eureka/
  server:
    # true表示开启自我保护模式,false表示关闭自我保护模式
    enable-self-preservation: true
    # 清理间隔(单位:毫秒,默认60*1000)
    eviction-interval-timer-in-ms: 60000
