server:
  # ???
  port: 8761

spring:
  application:
    # ????
    name: eureka-server

# ??Eureka Server????
eureka:
  instance:
    # ???, ?????????????????????
    hostname: localhost
  client:
    # ????????????,???true
    registerWithEureka: false
    # ???????????????,???true
    fetchRegistry: false
    # ?????????????
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
